DROP TRIGGER IF EXISTS `Stundenplan`.`VERTETENDERDOZENT_AFTER_INSERT`;

DELIMITER $$
USE `Stundenplan`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Stundenplan`.`VERTETENDERDOZENT_AFTER_INSERT` AFTER INSERT ON `vertretenderDozent` FOR EACH ROW
BEGIN
	CALL erstelleHistorieneintrag(NEW.terminId, 'Vertretung');
END$$
DELIMITER ;

